I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 278, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/J1min/Documents/renpy-8.0.3-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/Users/J1min/Documents/renpy-8.0.3-sdk/renpy/main.py", line 660, in main
    run(restart)
  File "/Users/J1min/Documents/renpy-8.0.3-sdk/renpy/main.py", line 146, in run
    renpy.execution.run_context(True)
  File "/Users/J1min/Documents/renpy-8.0.3-sdk/renpy/execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "/Users/J1min/Documents/renpy-8.0.3-sdk/renpy/script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
안녕하세요. 회귀한 만렙 백엔드 개발자입니다. 1.0
Fri Mar 17 11:58:24 2023
