I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script
    1나 "내가 다시 그때로 돌아갈 수만 있다면..."
Exception: Sayer b'1' is not a function or string.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script
    1나 "내가 다시 그때로 돌아갈 수만 있다면..."
  File "/Volumes/renpy-8.0.3-sdk/renpy-8.0.3-sdk/renpy/ast.py", line 898, in execute
    raise Exception("Sayer %s is not a function or string." % self.who.encode("utf-8"))
Exception: Sayer b'1' is not a function or string.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
안녕하세요. 회귀한 만렙 백엔드 개발자입니다. 1.0
Fri Mar 17 10:23:20 2023
